[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
InsecureUnlockAllowed = false
HTTPPort = 8585
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8586
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 600
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false
TrustedNodes=["enode://72ab079154c43997d1d3c8c6cb2de153f0f7be39a0be3bc562e39a7fa21909691bbbb8353792210e10c603531dc09bdb2b9724d8ebcddac76eb230071e6a657a@35.174.116.33:30311"]

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""


